version: "3.9"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password123
    links:
      - phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: password123
